name: CMake Build
on:
  push:
    branches: 
      - main
      - master
  pull_request:
    branches: 
      - main
      - master

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        # https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
        include:
          - os: ubuntu-24.04
            os-type: debian
          # Mac OS X - 13 runs on intel
          - os: macos-13
            os-type: darwin
    runs-on: ${{ matrix.os }}

    steps:
      # Checkout moos-ivp-umassd
    - uses: actions/checkout@v4
      with:
        path: moos-ivp-umassd

      # Checkout moos-ivp
    - uses: actions/checkout@v4
      with:
        repository: moos-ivp/moos-ivp
        path: moos-ivp

    - name: Install Dependencies - Debian/Ubuntu
      if: matrix.os-type == 'debian'
      run: |
        sudo apt-get update -y
        sudo apt-get install -y cmake build-essential git libtiff5-dev libfltk1.3-dev freeglut3-dev libpng-dev libjpeg-dev libxinerama-dev libxft-dev

    - name: Install Dependencies - Mac OS X
      if: matrix.os-type == 'darwin'
      run: |
         brew install fltk libtiff autoconf automake
      shell: bash

    - name: Build moos-ivp
      run: ./build.sh
      working-directory: moos-ivp

    - name: Check moos-ivp
      run: ./build-check.sh
      working-directory: moos-ivp

    - name: Build moos-ivp-umassd
      run: ./build.sh
      working-directory: moos-ivp-umassd
